# Generated by Django 4.0.6 on 2022-07-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0002_remove_photo_photo_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
